[workspace]
authors = ["Kamil Kania <kkania388@gmail.com>"]
channels = ["conda-forge"]
name = "lab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
lab03 = "bash bash_scripts/lab03.sh"
lab04 = "bash bash_scripts/lab04.sh"
lab05 = "bash bash_scripts/lab05.sh"
lab06 = "bash bash_scripts/lab06.sh"
lab07 = "bash bash_scripts/lab07.sh"

test = { depends-on =
  [
    "lab03",
    "lab04",
    "lab05",
    "lab06",
    "lab07",
  ]
}

[dependencies]
matplotlib = ">=3.11.1,<4"
pandas = ">=3.0.5,<4"
uv = ">=0.12.12,<0.13"
ffmpeg = ">=9.0.1,<10"
