[project]
name = "lab04-virus-automaton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kamil Kania", email = "kkania388@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "seaborn>=0.13.2",
]

[project.scripts]
lab04-virus-automaton = "lab04_virus_automaton:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
